### ISSUE TITLE
Terraform modules dependencies locally configuration (`when_modified`)

### ISSUE THREAD

**Issue by arthur-leclerc** [transcend-io/terragrunt-atlantis-config#154]
Hello,

Would it be possible to support the generation of Terraform modules path in `when_modified` as an option?

We have the following file structure in a monorepo:

```bash
├── live
│   ├── service-1
│   │   └── terragrunt.hcl # use root-module-1
│   └── service-2
│       └── terragrunt.hcl # use root-module-2
└── terraform
    ├── modules # terraform modules
    │   └── module-1
    │   └── module-2 # use module-3
    │   └── module-3 
    └── root-modules # terragrunt modules
        └── root-module-1 # use `module-1`
        └── root-module-2 # use `module-1` and `module-2`
```

We mainly use Terragrunt and Terraform without ref, which implies that we do not use a version in the Terragrunt/Terraform source blocks, so when modifying a Terraform module (`module-1`) for example, no change is made to `root-module-1` and therefore, with the current generation of `terragrunt-atlantis-config`, change can not be taking into account by Atlantis.

The Atlantis file looks like this:

```yaml
automerge: false
parallel_apply: true
parallel_plan: true
projects:
- autoplan:
    enabled: true
    when_modified:
    - '*.hcl'
    - '*.tf*'
    - ../../terraform/root-modules/root-module-1/*.tf*
  dir: service-1
  workflow: terragrunt
- autoplan:
    enabled: true
    when_modified:
    - '*.hcl'
    - '*.tf*'
    - ../../terraform/root-modules/root-module-2/*.tf*
  dir: service-2
  workflow: terragrunt
version: 3
```

And we would be able to withstand an output like this:

```yaml
automerge: false
parallel_apply: true
parallel_plan: true
projects:
- autoplan:
    enabled: true
    when_modified:
    - '*.hcl'
    - '*.tf*'
    - ../../terraform/modules/module-1/*.tf*
    - ../../terraform/root-modules/root-module-1/*.tf*
  dir: service-1
  workflow: terragrunt
- autoplan:
    enabled: true
    when_modified:
    - '*.hcl'
    - '*.tf*'
    - ../../terraform/modules/module-2/*.tf*
    - ../../terraform/modules/module-3/*.tf*
    - ../../terraform/root-modules/root-module-2/*.tf*
  dir: service-2
  workflow: terragrunt
version: 3
```

[hashicorp/terraform-config-inspect](https://github.com/hashicorp/terraform-config-inspect) performed in cascade in order to obtain all the modules can maybe be a solution to achieve this result.

```bash
> terraform-config-inspect terraform/root-modules/root-module-1 --json | jq .module_calls

{
  "module_1": {
    "name": "module_1",
    "source": "../../modules/module-1",
    ...
  }
}
```

A complete example of the monorepo structure can be found [there](https://github.com/arthur-leclerc/terragrunt-monorepo).

I hope that the problem is well explained, I remain available for further information if necessary.
