### ISSUE TITLE
terragrunt-atlantis-config not being executed

### ISSUE THREAD

**Issue by pkaramol** [transcend-io/terragrunt-atlantis-config#165]
I am starting my `atlantis` server with the following flags

```
export AWS_ACCESS_KEY_ID=XXX && export AWS_SECRET_ACCESS_KEY=XXX && atlantis server --atlantis-url=http://1.1.1.1 --port=4242 --gh-user=pkaramol --gh-token=XXX --gh-webhook-secret=XXX --gh-hostname=github.com --repo-allowlist='github.com/pkaramol/atlantis-poc' --log-level=debug --repo-config=repoconfig.json
```

where 

```
{
  "repos": [
    {
      "id": "github.com/pkaramol/atlantis-poc",
      "workflow": "default",
      "pre_workflow_hooks": [
        {
          "run": "terragrunt-atlantis-config generate --output atlantis.yaml --autoplan --parallel --create-workspace"
        }
      ]
    }
  ]
}
```

However, upon `atlantis plan` execution everything fails and it seems the plain `terraform` command is being executed

```
running "/usr/local/bin/terraform plan -input=false -refresh -no-color -out \"/home/ubuntu/.atlantis/repos/pkaramol/atlantis-poc/2/default/default.tfplan\"" in "/home/ubuntu/.atlantis/repos/pkaramol/atlantis-poc/2/default": exit status 1

Error: No configuration files

Plan requires configuration to be present. Planning without a configuration
would mark everything for destruction, which is normally not what is desired.
If you would like to destroy everything, run plan with the -destroy option.
Otherwise, create a Terraform configuration file (.tf file) and try again.
```

For repo `id` I have also tried using the value of `/.*/` 

Using `atlantis` `0.17.3` on `Ubuntu 20.04.3` as also `terragrunt-atlantis-config` `1.8.1`

`atlantis` debug-level [logs](https://gist.github.com/pkaramol/ce9209d251150abb47ee59447c6d896c).

**Comment by dmattia** [comment]
From what I can tell, it looks like `terragrunt-atlantis-config` is running, but during your `plan` workflow you are using `terraform` instead of `terragrunt`.

Can you confirm if you've gone through the steps on Atlantis to use Terragrunt as your runner? https://www.runatlantis.io/docs/custom-workflows.html#use-cases

I'm going to close for now, but if I've misunderstood or those directions don't work for you, please feel free to re-open this Issue 😄

**Comment by pkaramol** [comment]
Sorry, I thought initiating `atlantis` with this server side repo config

```
{
  "repos": [
    {
      "id": "github.com/pkaramol/atlantis-poc",
      "workflow": "default",
      "pre_workflow_hooks": [
        {
          "run": "terragrunt-atlantis-config generate --output atlantis.yaml --autoplan --parallel --create-workspace"
        }
      ]
    }
  ]
}
```

would be enough (I assumed it would generate the `atlantis.yaml` file and there would be no need on my end for sth else.

Will give it a try and let you know.

**Comment by pkaramol** [comment]
Here is what I get now: 

Starting server with the following config

```
{
  "repos": [
    {
      "id": "pkaramol/atlantis-poc-v2",
      "workflow": "default",
      "allowed_overrides": ['workflow'],
      "pre_workflow_hooks": [
        {
          "run": "terragrunt-atlantis-config generate --output atlantis.yaml --autoplan --parallel --create-workspace"
        }
      ]
    }
  ]
}
```

and my `atlantis.yaml` in the repo

```
version: 3
projects:
- dir: live/non-prod/
  apply_requirements: [mergeable]
  workflow: default
- dir: live/prod/
  apply_requirements: [mergeable]
  workflow: default
workflows:
  default:
    plan:
      steps:
      - run: terragrunt plan -no-color --terragrunt-non-interactive -out $PLANFILE
    apply:
      steps:
      - run: terragrunt apply --terragrunt-non-interactive -no-color $PLANFILE

```
