### ISSUE TITLE
Documentation missing on ignore line in generate output from local execution

### ISSUE THREAD

**Issue by pantelis-karamolegkos** [transcend-io/terragrunt-atlantis-config#204]
I have installed `terragrunt-atlantis-config` locally and I am running a `terragrunt-atlantis-config generate` on one of my projects.

Here is the output

```yaml
projects:
- autoplan:
    enabled: false
    when_modified:
    - '*.hcl'
    - '*.tf*'
    - ../modules/mymodules/module1/*.tf*
    - ../modules/mymodules/module2/*.tf*
    - ignore
    - ../somevars.tfvars
    - ../config.auto.tfvars
    - ../../../someother.auto.tfvars
  dir: .
```

What is the `- ignore` line? I didn't find any documentation on this.
