### ISSUE TITLE
Error when trying to run plan in a directory that does not contain terragrunt.hcl file

### ISSUE THREAD

**Issue by pantelis-karamolegkos** [transcend-io/terragrunt-atlantis-config#205]
I have the following `repoConfig.yaml` 

```yaml
    - run: terragrunt-atlantis-config generate --output atlantis.yaml --autoplan --parallel --create-workspace
workflows:
  terragrunt:
    plan:
      steps:
      - run: terragrunt plan -no-color -out=$PLANFILE
      - run: terragrunt show -no-color -json $PLANFILE > $SHOWFILE
    apply:
      steps:
      - run: terragrunt apply -no-color $PLANFILE
```

In one of my `PRs` I modified the following file:

```
terragrunt/live/something/somethingelse/config.auto.tfvars
```

The directory `terragrunt/live/something/somethingelse` does not contain a `terragrunt.hcl` file.

So the plan failed

```
time=2022-02-24T12:49:18Z level=error msg=Error reading file at path /home/atlantis/.atlantis/repos/MyOrg/myrepo/2096/default/terragrunt/live/something/somethingelse/terragrunt.hcl: open /home/atlantis/.atlantis/repos/MyOrg/myrepo/2096/default/terragrunt/live/something/somethingelse/terragrunt.hcl: no such file or directory
```

Is this expected?
