### ISSUE TITLE
Terragrunt plan fails with Failed to get existing workspaces: querying Cloud Storage failed: storage: bucket doesn't exist

### ISSUE THREAD

**Issue by pantelis-karamolegkos** [transcend-io/terragrunt-atlantis-config#211]
I have installed `atlantis` on a GCP that has a GCP/IAM service account that allows it to perform all relevant operations.

This is crossed-check since when I login to the VM I run all `terragrunt plan` / `terragrunt apply` operations without using my own personal GCP account, but rather the machine's account.

I have installed `atlantis` as a `systemd` service on the VM and it runs with the same-name user (`atlantis`)

I have the following server side repo config

```yaml
repos:
- id: "/.*/" # (or <your_repo_id>)
  allow_custom_workflows: true
  workflow: terragrunt
  apply_requirements: [approved, mergeable]
  pre_workflow_hooks:
    - run: git-crypt unlock
    - run: terragrunt-atlantis-config generate --output atlantis.yaml --autoplan --parallel --create-workspace
workflows:
  terragrunt:
    plan:
      steps:
      - run: git-crypt unlock
      - run: terragrunt plan -no-color -out=$PLANFILE
      - run: terragrunt show -no-color -json $PLANFILE > $SHOWFILE
    apply:
      steps:
      - run: terragrunt apply -no-color $PLANFILE
```

Here is a small section of the auto-generated `atlantis.yaml` file (showing here just one project, but the pattern is more or less the same for all projects)

```yaml
automerge: false
parallel_apply: true
parallel_plan: true
projects:
- autoplan:
    enabled: true
    when_modified:
    - '*.hcl'
    - '*.tf*'
    - ../../../../modules/foo/bar/*.tf*
    - ../../config.tfvars
  dir: terragrunt/live/something/somethingelse/some
  workspace: terragrunt_live_something_somethingelse_some
```

I create a PR in which multiple files are changed.

Problem: everything (all plans corresponding to the workspaces of each project that has changes) fails as follows:

```
exit status 1: running "terragrunt plan -no-color -out=$PLANFILE" in "/home/atlantis/.atlantis/repos/MyOrg/myrepo/2144/terragrunt_live_something_somethingelse_tgmodule/terragrunt/live/something/somethingelse/tgmodule": 

Initializing the backend...

Successfully configured the backend "gcs"! Terraform will automatically
use this backend unless the backend configuration changes.

Error: Failed to get existing workspaces: querying Cloud Storage failed: storage: bucket doesn't exist


time=2022-03-07T16:01:26Z level=error msg=1 error occurred:
	* exit status 1
```

**Here comes the actually weird part**

In order for me to try to reproduce the issue by running a manual `terragrunt plan`, I `ssh` into the VM. I then switch to the specific user (`atlantis`) and cd into `/home/atlantis/.atlantis/repos/MyOrg/myrepo/2144/terragrunt_live_something_somethingelse_tgmodule/terragrunt/live/something/somethingelse/tgmodule`

(to reproduce as closely as possible the problem by running the exact same command as the same user that creates the PR comment with the failure)

First attempt for `terragrunt plan`

```
$ terragrunt plan -no-color
Initializing modules...

Initializing the backend...
╷
│ Error: Backend configuration changed
│
│ A change in the backend configuration has been detected, which may require
│ migrating existing state.
│
│ If you wish to attempt automatic migration of the state, use "terraform
│ init -migrate-state".
│ If you wish to store the current configuration with no changes to the
│ state, use "terraform init -reconfigure".
╵
```

I remove the cache

```
$ rm -rf .terragrunt-cache/
```

After that, when I try again `terragrunt plan`, the `plan` proceeds...

I am a bit stuck all day with that weird situation so any help/hint would be super-highly appreciated
