### ISSUE TITLE
Terragrunt dependency blocks: why only check for changes to terragrunt.hcl?

### ISSUE THREAD

**Issue by mustafa89** [transcend-io/terragrunt-atlantis-config#223]
Thanks for this great tool!

Everything works as intended, I just had a small question regarding dependencies.

I see that when we have a dependency block in the `terragrunt.hcl` of say `main-web-app` project, and it depends on the output from the `iam-roles` project
```hcl

# main-web-app/terragrunt.hcl
dependency "iam_roles" {
  config_path = "../iam-roles"
  mock_outputs = {
    role_arn = "placeholder"
  }
}

inputs = {
  role_arn = dependency.iam_roles.outputs.role_arn
}
```

why does the `atlantis.yaml` only check the single `../iam-roles/terragrunt.hcl` file for changes.

```hcl
- autoplan:
    enabled: true
    when_modified:
    - '*.hcl'
    - '*.tf*'
    - ../terragrunt.hcl
    - ../iam-roles/terragrunt.hcl
  dir: infrastructure/dev/us-east-1/main-web-app
```

What if I delete that output for `role_arn` that `main-web-app` depend on? since I made no change to the terragrunt.hcl the change goes unnoticed, and the next time i run terragrunt in the `main-web-app` directory, we will get an error. 

Maybe I'm missing something here, If you could please advise here, would be appreciated. Thanks.

**Comment by mustafa89** [comment]
hello, would be great if someone could guide on the intended use case. If this is bug I'll try and create a PR for this. Many thanks :)

**Comment by mustafa89** [comment]
Hey, there are no modules in my example, `main-web-app` and `iam-roles` are terragrunt projects at the same level in a dir. 

> so I would have expected main-web-app to not only list terragrunt.hcl from iam-roles, but also the .tf and other related files iam-roles depends on

Exactly, and it does not do that.

I'm using version: `1.14.2`

**Comment by dmattia** [comment]
Could you open a PR adding these files (can use dummy data) to the `test_examples` folder? I can then run some e2e tests and make sure the output is as expected with any fixes

**Comment by megakid** [comment]
I am also seeing this behavior which I found odd.

I have one 'leaf' terraform module in a folder called `myapp/k8s` which declares a terragrunt dependency on `myapp/main` (or more precisely, `../main`).  I use terragrunt to pass some outputs from the `main` module to `k8s` module.  Both modules also reference other local modules using the standard terraform `module` resource blocks.

`terragrunt-atlantis-config generate --output bleb.yaml --autoplan --parallel --create-workspace --execution-order-groups`

The output I get is:
```
...
- autoplan:
    enabled: true
    when_modified:
    - '*.hcl'
    - '*.tf*'
    - ../../terragrunt.hcl
    - ../../../../modules/aks/*.tf*
    - ../../../../modules/custom-dns-zone/*.tf*
    - ../../../../modules/storage_account/*.tf*
  dir: terraform/azure/tf/environments/tnd/dremio/main
  workspace: terraform_azure_tf_environments_tnd_dremio_main
- autoplan:
    enabled: true
    when_modified:
    - '*.hcl'
    - '*.tf*'
    - ../../terragrunt.hcl
    - ../main/terragrunt.hcl
    - ../../../../modules/aks/*.tf*
    - ../../../../modules/custom-dns-zone/*.tf*
    - ../../../../modules/storage_account/*.tf*
  dir: terraform/azure/tf/environments/tnd/dremio/k8s
  execution_order_group: 1
  workspace: terraform_azure_tf_environments_tnd_dremio_k8s
...
```

I would have expected the `../main/terragrunt.hcl` line to also have an associated `*.tf*` line.
