### ISSUE TITLE
Parent Terragrunt is included as dependency

### ISSUE THREAD

**Issue by enarmontas** [transcend-io/terragrunt-atlantis-config#235]
Here is my parent `terragrunt.hcl`:
```
locals {
  account_vars = read_terragrunt_config(find_in_parent_folders("account.hcl"))
  project_vars = read_terragrunt_config(find_in_parent_folders("project.hcl"))
  region_vars  = read_terragrunt_config(find_in_parent_folders("region.hcl"))

  aws_account_id  = local.account_vars.locals.account_id
  aws_region_name = local.region_vars.locals.region_name
}

# Generate backend
remote_state {
  backend = "consul"
  generate = {
    path      = "backend.tf"
    if_exists = "overwrite"
  }
  config = {
    lock         = true
    path         = "terraform-state/${path_relative_to_include()}/terraform.tfstate"
    scheme       = "http"
  }
}

# Generate provider
generate "provider" {
  path      = "provider.tf"
  if_exists = "overwrite_terragrunt"
  contents  = <<-EOF
provider "aws" {
  region              = "${local.aws_region_name}"
  allowed_account_ids = ["${local.aws_account_id}"]
}
EOF
}
```
Here is my child `terragrunt.hcl`
```
terraform {
  source = "git::git@github.com:terraform-aws-modules/terraform-aws-iam.git//modules/iam-user?ref=v5.1.0"
}

include {
  path = find_in_parent_folders()
}

inputs = {
  name = "example-two"
}
```
Here is the command I run:
```
terragrunt-atlantis-config generate --output atlantis.yaml --autoplan --create-workspace --parallel --ignore-parent-terragrunt
```
And here is the resulting Atlantis config:
```
automerge: false
parallel_apply: true
parallel_plan: true
projects:
- autoplan:
    enabled: true
    when_modified:
    - '*.hcl'
    - '*.tf*'
    - ../../../../../terragrunt.hcl
  dir: test/example/global/iam-user/example-two
  workspace: test_example_global_iam-user_example-two
version: 3
```
Why does it include the parent config `../../../../../terragrunt.hcl`? Is there a bug or I am doing something wrong?
