### ISSUE TITLE
Handling folder/project removal 

### ISSUE THREAD

**Issue by keviiin38** [transcend-io/terragrunt-atlantis-config#239]
Hello,

I'm testing this neat tool, but I can't figure out how to handle a folder/project removal, in order to destroy the associated ressources...

My folder structure :

```
├── apps
│   ├── app1
│   │   └── terragrunt.hcl
│   └── app2
│       └── terragrunt.hcl
├── modules
│   └── app
│       └── main.tf
└── terragrunt.hcl
```

My server-side Atlantis repo config :

```yaml
repos:
  - id: /.*/
    workflow: default
    apply_requirements: [approved, mergeable]
    pre_workflow_hooks:
      - run: terragrunt-atlantis-config generate --output atlantis.yaml --autoplan --parallel --create-workspace

workflows:
  default:
    plan:
      steps:
        - run: terragrunt plan -out=$PLANFILE
    apply:
      steps:
        - run: terragrunt apply $PLANFILE
```

If I add a new folder in `apps/` everything is okay, but if I remove a folder, Atlantis says `Ran Plan for 0 projects:`...

```diff
 ├── apps
 │   ├── app1
 │   │   └── terragrunt.hcl
-│   └── app2
-│       └── terragrunt.hcl
 ├── modules
 │   └── app
 │       └── main.tf
 └── terragrunt.hcl
```

I now understand why, because the folder isn't present anymore, thus not detected for the generated projects list, which seems logic.

How should I configure the tool in order to get removed folders being destroyed from state, etc... ?

Thanks in advance !
