### ISSUE TITLE
Different workflow for different projects

### ISSUE THREAD

**Issue by RonLek** [transcend-io/terragrunt-atlantis-config#240]
The usual repo level `atlantis.yaml` file allows specifying a workflow per project. Example:
```yaml
version: 3
projects:
- dir: live/human
  workflow: terragrunt
- dir: live/machine
  workflow: terragruntjson
workflows:
  terragrunt:
    plan:
      steps:
      - run: terragrunt plan -out $PLANFILE
    apply:
      steps:
      - run: terragrunt apply $PLANFILE
   terragruntjson:
    plan:
      steps:
      - run: terragrunt plan -json -out $PLANFILE
    apply:
      steps:
      - run: terragrunt apply -json $PLANFILE
```
In the above example, I run different workflows (`terragrunt` and `terragruntjson`) depending on the directory my terragrunt resides in (`live/human` or `live/machine`). 

Unfortunately this doesn't seem possible when using `terragrunt-atlantis-config` since with the `--workflow` flag it adds the same workflow for all directories within the same repo. 

A support to customize `--workflow` based on directory would be really helpful since atlantis supports this out of the box.
