### ISSUE TITLE
Limit autoplan to first order group

### ISSUE THREAD

**Issue by stdmje** [transcend-io/terragrunt-atlantis-config#263]
Hey, 

First of all thanks for developing such an amazing tool!

I am doing some tests for using Atlantis + terragrunt-atlantis-config and i am struggling with dependencies.

My question is:

Can i limit only plan/apply to modules that are only in the first group of execution?

Right now i have autoplan enabled and obviously when a module is dependent of an output from another module that has not been applied, it will fail.

Most of our code is for deploying helm charts in k8s so having a mock in the dependency block is not the best approach for our use case.

Here is my config:
``` 
  repos:
  - id: /.*/
    delete_source_branch_on_merge: true
    apply_requirements: [mergeable]
    allowed_workflows: [terragrunt]
    workflow: terragrunt
    pre_workflow_hooks:
    - run: terragrunt-atlantis-config generate --filter "terragrunt/clients/[a-z]*" --output atlantis.yaml --autoplan --parallel=false --execution-order-groups=true
  workflows:
    terragrunt:
      plan:
        steps:
        - run: terragrunt plan -no-color -lock=false -out=$PLANFILE
        - run: terragrunt show -json $PLANFILE > $SHOWFILE
      apply:
        steps:
        - run: terragrunt apply -no-color -auto-approve
```

I don't like to have fails in our plan because it creates confusion to the creator/reviewer of the PR so this is why i would like to run only plan/apply to the first group and forget about everything else.

Thanks a lot for your help
