### ISSUE TITLE
bug: execution_order_group does not work with a folder without *.hcl files in the file structure

### ISSUE THREAD

**Issue by SimonG-Alza** [transcend-io/terragrunt-atlantis-config#325]
## Bug report

Using `terragrunt-atlantis-config generate --output atlantis.yaml --create-workspace --create-project-name --execution-order-groups true` in my terragrunt project, which contains folders without *.hcl files in the file structure.

**To Reproduce**

1. Download test_examples/terragrunt_dependency from https://github.com/transcend-io/terragrunt-atlantis-config/tree/master/test_examples/terragrunt_dependency.
2. Create file structure as:
![image](https://github.com/transcend-io/terragrunt-atlantis-config/assets/161483070/585d48ba-0fdf-447e-a79c-750c9a017979)
3. Run `terragrunt-atlantis-config generate --output atlantis.yaml --create-workspace --create-project-name --execution-order-groups true` in **test_examples**

Doesn't work if you run `terragrunt-atlantis-config generate --output atlantis.yaml --create-workspace --create-project-name --execution-order-groups true` in **test_examples/terragrunt_dependency** and you nested the depender as in
![image](https://github.com/transcend-io/terragrunt-atlantis-config/assets/161483070/7fa8c6c7-2d5c-4463-bf29-5b1450f2b084)

**Expected behavior**
```
automerge: false
parallel_apply: true
parallel_plan: true
projects:
- autoplan:
    enabled: false
    when_modified:
    - '*.hcl'
    - '*.tf*'
  dir: dependency
  name: dependency
  workspace: dependency
- autoplan:
    enabled: false
    when_modified:
    - '*.hcl'
    - '*.tf*'
    - ../dependency/terragrunt.hcl
  dir: depender
  **execution_order_group: 1**
  name: depender
  workspace: depender
version: 3
```

**Actual behavior**

```
automerge: false
parallel_apply: true
parallel_plan: true
projects:
- autoplan:
    enabled: false
    when_modified:
    - '*.hcl'
    - '*.tf*'
  dir: terragrunt_dependency/dependency
  name: terragrunt_dependency_dependency
  workspace: terragrunt_dependency_dependency
- autoplan:
    enabled: false
    when_modified:
    - '*.hcl'
    - '*.tf*'
    - ../dependency/terragrunt.hcl
  dir: terragrunt_dependency/depender
  name: terragrunt_dependency_depender
  workspace: terragrunt_dependency_depender
version: 3
```

**Relevant Terragrunt files**
Using https://github.com/transcend-io/terragrunt-atlantis-config/tree/master/test_examples/terragrunt_dependency
