### ISSUE TITLE
execute atlantis operations using group tags on projects

### ISSUE THREAD

**Issue by pseudomorph** [transcend-io/terragrunt-atlantis-config#333]
## Feature Request

- [x] I'd be willing to implement this feature

**Describe the idea**

Atlantis allows the ability to run targeted operations by specifying `project`, `dir`, and `workspace`. This ability is currently very powerful, and could be vastly improved by allowing projects to be grouped by arbitrary tags.

This configuration could look something like:

`atlantis.yaml`
```
...
projects:
- autoplan:
    enabled: true
    when_modified:
    - file1
    -file2
  dir: /project/dir/path
  name: projectname
  execution_group_tags:
  - <some-environment>
  - <some-project-type>
  - etc....
```

and would be used in this way:

```
atlantis plan -t "<some-project-type>"
```

**Why is this helpful?**

This would allow a broader capability to execute operations on discreet sets of projects.

**What alternatives exist today?**

N/A
