### ISSUE TITLE
Example Atlantis Workplan

### ISSUE THREAD

**Issue by sbquinlan** [transcend-io/terragrunt-atlantis-config#346]
## Feature Request

Please document an example Atlantis workplan that works with the example `terragrunt-atlantis-config` pre_workflow_hooks in the documentation: 

```
      "workflow": "default",
      "pre_workflow_hooks": [
        {
          "run": "terragrunt-atlantis-config generate --output atlantis.yaml --autoplan --parallel --create-workspace"
        }
      ]
```

**Why is this helpful?**

While I don't expect `terragrunt-atlantis-config` to re-document all the Atlantis workplan options and configuration, an example workplan would go a long way. 

**What alternatives exist today?**

The Atlantis documentation provides example workplans for terragrunt in their [Custom Workflows]() section. This example does not support the workspaces that the example `terragrunt-atlantis-config` recommends (`--parallel --create-workspace`). This leaves me reverse engineering the workplan that might work with this config.

```
workflows:
  terragrunt:
    plan:
      steps:
      - env:
          name: TERRAGRUNT_TFPATH
          command: 'echo "terraform${ATLANTIS_TERRAFORM_VERSION}"'
      - env:
          # Reduce Terraform suggestion output
          name: TF_IN_AUTOMATION
          value: 'true'
      - run:
          # Allow for targetted plans/applies as not supported for Terraform wrappers by default
          command: terragrunt plan -input=false $(printf '%s' $COMMENT_ARGS | sed 's/,/ /g' | tr -d '\\') -no-color -out $PLANFILE
          output: hide
      - run: |
          terragrunt show $PLANFILE
```
