### ISSUE TITLE
Issues with mutliple depends on when using extra_arguments

### ISSUE THREAD

**Issue by trahim** [transcend-io/terragrunt-atlantis-config#365]
## Bug report

When generating using `--depends-on` and `extra_arguments` in the terraform block, you end up with repeated dependencies

**To Reproduce**

Summarize how to reproduce the behavior. For example:
1. Create a dependency terragrunt file that looks like
```
terraform {
  source = "git::git@github.com:transcend-io/terraform-aws-fargate-container?ref=v0.0.4"
  extra_arguments "extra" {
    commands = get_terraform_commands_that_need_vars()
    optional_var_files = [
      "${get_terragrunt_dir()}/extra.tfvars",
    ]
  }
}

inputs = {
  foo = "bar"
}
```
2. Run the command `terragrunt-atlantis-config generate --output atlantis.yaml --autoplan --parallel --depends-on --create-project-name`

**Expected behavior**

Output to look like
```
automerge: false
parallel_apply: true
parallel_plan: true
projects:
- autoplan:
    enabled: true
    when_modified:
    - '*.hcl'
    - '*.tf*'
    - extra.tfvars
  dir: dependency
  name: dependency
- autoplan:
    enabled: true
    when_modified:
    - '*.hcl'
    - '*.tf*'
    - ../dependency/terragrunt.hcl
    - ../dependency/extra.tfvars
  depends_on:
  - dependency
  - dependency
  dir: depender
  name: depender
version: 3
```

**Actual behavior**

Extra dependency
```
automerge: false
parallel_apply: true
parallel_plan: true
projects:
- autoplan:
    enabled: true
    when_modified:
    - '*.hcl'
    - '*.tf*'
    - extra.tfvars
  dir: dependency
  name: dependency
- autoplan:
    enabled: true
    when_modified:
    - '*.hcl'
    - '*.tf*'
    - ../dependency/terragrunt.hcl
    - ../dependency/extra.tfvars
  depends_on:
  - dependency
  dir: depender
  name: depender
version: 3
```

**Relevant Terragrunt files**

I've created a PR with test scenarios, where I've just made the append to `dependsOnList` only allow unique project names. It might be a primitive solution but should handle any future use cases. but open to suggestions.
