### ISSUE TITLE
Can't destroy resources

### ISSUE THREAD

**Issue by TobiPeterG** [transcend-io/terragrunt-atlantis-config#368]
## Bug report

I want to destroy resources I created using terragrunt-atlantis-config. However, the mentioned method in https://github.com/transcend-io/terragrunt-atlantis-config/issues/291 with "atlantis plan - -destroy" doesn't work for me. Atlantis plans normally, ignoring the -destroy flag:
`atlantis plan -- -destroy`
```
terraform_data.mac_md5["dhc-cloud-dhcp"]: Refreshing state... [id=a683de9e-9ff8-ae1b-960e-87498357d3a0]
module.nautobot_ip.data.nautobot_vlan.vlans["dhc-cloud-dhcp"]: Reading...
module.nautobot_vm.data.nautobot_cluster.vm_cluster: Reading...
module.nautobot_ip.data.nautobot_prefixes.prefixes: Reading...
module.cloudinit_config.data.cloudinit_config.vm: Reading...
module.cloudinit_config.data.cloudinit_config.vm: Read complete after 0s [id=296859759]
module.puppet_cert.null_resource.puppet_cert: Refreshing state... [id=2708420698625234559]
module.mgmt_assignment.data.mgmt_user.assigned_users["Test.Testface"]: Reading...
module.mgmt_vm_host.mgmt_host.vm: Refreshing state... [id=257]
module.mgmt_assignment.data.mgmt_user.assigned_users["Test.Testface"]: Read complete after 0s [id=13395]
module.vsphere_vm.data.vsphere_datacenter.dc: Reading...
module.mgmt_assignment.mgmt_assignment.vm-user["Test.Testface"]: Refreshing state... [id=257-13395]
module.vsphere_vm.data.vsphere_datacenter.dc: Read complete after 0s [id=datacenter-2]
null_resource.trigger_mgmt_sync: Refreshing state... [id=9077295307293691509]
module.vsphere_vm.data.vsphere_datastore.datastore: Reading...
module.vsphere_vm.data.vsphere_compute_cluster.cluster: Reading...
module.vsphere_vm.data.vsphere_network.network["dhc-cloud-dhcp"]: Reading...
module.vsphere_vm.data.vsphere_virtual_machine.template: Reading...
module.vsphere_vm.data.vsphere_network.network["dhc-cloud-dhcp"]: Read complete after 0s [id=dvportgroup-6860]
module.vsphere_vm.data.vsphere_datastore.datastore: Read complete after 0s [id=datastore-1219]
module.vsphere_vm.data.vsphere_compute_cluster.cluster: Read complete after 0s [id=domain-c7]
module.vsphere_vm.data.vsphere_virtual_machine.template: Read complete after 0s [id=42045b50-464e-de64-23bb-a37e44c5773d]
module.nautobot_vm.data.nautobot_cluster.vm_cluster: Read complete after 0s [id=86856181-8297-4f68-9283-f1a30f1213a9]
module.nautobot_vm.nautobot_virtual_machine.vm: Refreshing state... [id=4465790a-d72d-49e4-adb7-460f25b4eb3a]
module.nautobot_ip.data.nautobot_vlan.vlans["dhc-cloud-dhcp"]: Read complete after 0s [id=e3017c72-0b20-4713-9d3a-bf569ea4c366]
module.nautobot_ip.data.nautobot_prefixes.prefixes: Read complete after 6s [id=1736533752]
module.nautobot_ip.null_resource.filtered_prefixes["dhc-cloud-dhcp"]: Refreshing state... [id=647973911333096298]
module.nautobot_ip.nautobot_available_ip_address.vm_ip["dhc-cloud-dhcp"]: Refreshing state... [id=ebefa6f5-6ba2-4533-8e29-236447458dbc]
module.dhcp_entry[0].null_resource.dhcp_entry: Refreshing state... [id=7478134385000018714]
module.nautobot_int.nautobot_vm_interface.vm_eth0: Refreshing state... [id=870e44e1-fd53-444a-b6b0-f6b76a05e015]
module.dns_config[0].dns_a_record_set.dns_record: Refreshing state... [id=test-folders.cloud.dhclab.i.hpi.de.]
module.cloudinit_config.data.template_file.network_cloud_init: Reading...
module.cloudinit_config.data.template_file.network_cloud_init: Read complete after 0s [id=8b92e18dea4db1642626e6e2b461b1787bd5938094de0b4afc72fefd27286b36]
module.vsphere_vm.vsphere_virtual_machine.vm: Refreshing state... [id=4204058e-ac73-9029-10ad-a27a037c350c]
module.nautobot_int.nautobot_vm_primary_ip.vm_primary_ip: Refreshing state... [id=4465790a-d72d-49e4-adb7-460f25b4eb3a]

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration
and found no differences, so no changes are needed.
```

The only way to destroy resources for now is to manually do this.

**To Reproduce**

Summarize how to reproduce the behavior. For example:
1. Create a resource with atlantis
2. make a non-changing change to the project that should be destroyed
3. run `atlantis plan -- -destroy`
4. observe

**Expected behavior**

Altantis plans to destroy the resource

**Actual behavior**

Atlantis ignores the -destroy flag

**Relevant Terragrunt files**

This is the config we have:
repo.yaml
```
repos:
- id: "gitlab.instance.com/proj/proj2/proj3/repo"
  allowed_overrides: [workflow, apply_requirements]
  allow_custom_workflows: true
  workflow: terragrunt
  apply_requirements: [mergeable]
  pre_workflow_hooks:
    - run: terragrunt-atlantis-config generate --output atlantis.yaml --autoplan --parallel --create-workspace --automerge
workflows:
  terragrunt:
    plan:
      steps:
      - run: terragrunt plan -no-color -out=$PLANFILE
      - run: terragrunt show -no-color -json $PLANFILE > $SHOWFILE
    apply:
      steps:
      - run: terragrunt apply -no-color $PLANFILE

```

Can this be reproduced?
