### ISSUE TITLE
feature request: preserve existing workflows in atlantis.yaml output

### ISSUE THREAD

**Issue by russell-sherman-getupside** [transcend-io/terragrunt-atlantis-config#79]
if atlantis.yaml exists and includes custom workflows those should be persisted in the output

**Comment by dmattia** [comment]
The generated output supports custom workflows already, so I'm unsure what the defining characteristics would be for workflows that should be kept vs removed from the existing file.

Could you provide an example `atlantis.yaml` where you believe some workflows should be preserved? And in your example, how would this tool recognize that certain workflows should be kept?

I guess in general, it would be very easy for this tool to preserve existing fields, I'm just not sure why or how it would choose to save certain pre-existing data

**Comment by russell-sherman-getupside** [comment]
lets say i have defined an atlantis.yaml in my repo with the following content

```yml
version: 3
projects:
- dir: project1/acm
  workflow: terragrunt
- dir: project1/ecr
  workflow: terragrunt
- dir: project1/ecs
  workflow: terragrunt
- dir: project1/vpc
  workflow: terragrunt
workflows:
  terragrunt:
    plan:
      steps:
      - run: terragrunt plan -no-color -out $PLANFILE
    apply:
      steps:
      - run: terragrunt apply -no-color $PLANFILE
```

then i run a command to generate the config..

```sh
terragrunt-atlantis-config generate --ignore-parent-terragrunt --output ./atlantis.yaml --workflow terragrunt --create-project-name
```

the newly generated configuration will not include the custom workflow designated in the original file..

i am looking for some option flag(s) to allow me to define and recreate the workflows definitions or alternately have the existing workflows persisted into the regenerated document...
