### ISSUE TITLE
Local Terraform modules used as dependencies are not included in atlantis.yaml dependencies.

### ISSUE THREAD

**Issue by Neki** [transcend-io/terragrunt-atlantis-config#82]
Hi,

Thanks for this tool, it looks like it may solve a few workflow issues we're having. 
We're using local Terraform modules in the same repository as our Terragrunt configuration, and with this setup, it seems to me that terragrunt-atlantis-config may not include enough entries in its dependencies.

Consider the following structure:
```
├── live
│   ├── child
│   │   └── terragrunt.hcl
│   └── parent
│       └── terragrunt.hcl
└── modules
    ├── child
    │   └── main.tf
    └── parent
        └── main.tf
```
with the following contents
```hcl
# live/child/terragrunt.hcl
terraform {
  source = "../modules//child"
}

dependency "parent" {
  config_path = "../parent"
}

inputs = {
  input = dependency.parent.outputs.value
}

# live/parent/terragrunt.hcl 
terraform {
  source = "../modules//parent"
}

# modules/child/main.tf
locals {
  value = var.input
}

variable "input" {
  type = string
}

# modules/parent/main.tf 
locals {
  output = "whatever"
}

output "value" {
  value = local.output
}
```

`terragrunt-atlantis-config` generates the following `atlantis.yaml` (slightly edited to focus on the issue at hand)
```yaml
projects:
- autoplan:
    when_modified:
    - '*.hcl'
    - '*.tf*'
    - ../parent/terragrunt.hcl
    - ../modules/child/*.tf*
  dir: live/child
- autoplan:
    when_modified:
    - '*.hcl'
    - '*.tf*'
    - ../modules/parent/*.tf*
  dir: live/parent
```

Now, if I change in `module/parent/main.tf` the value of the local variable to "something else", it looks like it should prompt atlantis to also plan the child module - even if I did not change anything in the child module. In other words, `atlantis.yaml` should contain:
```yaml
projects:
- autoplan:
    when_modified:
    - '*.hcl'
    - '*.tf*'
    - ../parent/terragrunt.hcl
    - ../modules/child/*.tf*
    - ../modules/parent/*.tf*
  dir: live/child
```

The difference with local modules is that there's not always a change in the `terragrunt.hcl` file when the Terraform module changes.

In this example, the apply order is important: `terraform plan` will not detect any change if the `parent` module is not applied first and its output changed. I'm unclear however how this is different from a change in `parent/terragrunt.hcl` (which *is* included in the dependencies), because such a change could also alter the outputs of a module.

Do you think `terragrunt-atlantis-config` should support such a use case? I hope my explanations are clear enough :slightly_smiling_face:
