### ISSUE TITLE
Multiple plan for single hcl file change

### ISSUE THREAD

**Issue by mjagielka** [transcend-io/terragrunt-atlantis-config#85]
Hello ! 

We are currently using _terragrunt-atlantis-config_ to generate configurations for a large number of projects ( terragrunt dir's ) in our company. It seems that everything works for multiple projects but we have a strange problem with a simple use case. Updating terragrunt.hcl file in one module causes auto-plan for 44 modules, which is not the expected result. 

Details : 
Terragrunt version : v0.26.4
Terraform version : v0.13.3
terragrunt-atlantis-config version : 0.10.1

Command used to generate atlantis.yaml

_terragrunt-atlantis-config generate --output ./atlantis.yaml --autoplan --ignore-parent-terragrunt --parallel=false_

**Bitbucket Cloud PR** 
1x file updated ( new SA added to input block ) : platform/dev/prj/service_accounts/terragrunt.hcl 

```
# Pull in the backend and provider configurations from a root terragrunt.hcl file that you include in each child terragrunt.hcl:
include {
  path = find_in_parent_folders()
}

# Set the source to an immutable released version of the infrastructure module being deployed:
terraform {
  source = "github.com/terraform-google-modules/terraform-google-service-accounts?ref=v3.0.0"
}

locals {
  atlantis_workflow = "terragrunt-dev"
}

dependency "project" {
  config_path = "${get_terragrunt_dir()}/../global/project"
}

# Configure input values for the specific environment being deployed:
inputs = {
  project_id = dependency.project.outputs.project_id
  names = [“NAME_1”,
    “NAME_2”,
    “NAME_3” < — added in current PR
  ]
}
```

Part of the atlantis.yaml configuration responsible for the auto plan for this folder

```
automerge: false
parallel_apply: false
parallel_plan: false
projects:
***
- autoplan:
    enabled: true
    when_modified:
    - '*.hcl'
    - '*.tf*'
    - ../global/project/terragrunt.hcl
    - ../../../common.tfvars
  dir: platform/dev/prj/service_accounts
***
version: 3
workflows:
  terragrunt-dev:
***

```
Info from Atlantis pod :

_Successfully parsed atlantis.yaml file
44 projects are to be planned based on their when_modified config_

**Results** 
Auto plan for hcl files that are not directly related to the modification in PR

**Expected Results** 

Auto plan for changed file in PR + file from dependencies block ( ../global/project/terragrunt.hcl ) and terraform block ( ../../../common.tfvars). I can see plan execution for folders that are completely unrelated to the current PR changes

Thanks for any suggestions/ideas
