### ISSUE TITLE
any way to add custom files in "when_modified" when using terragrunt-atlantis-config

### ISSUE THREAD

**Issue by IamGabrielWu** [transcend-io/terragrunt-atlantis-config#87]
I run below command
```
terragrunt-atlantis-config generate --workflow terragrunt --ignore-parent-terragrunt --autoplan --output atlantis.yaml
```
it generates atlantis.yaml as below 
```
automerge: false
parallel_apply: true
parallel_plan: true
projects:
- autoplan:
    enabled: true
    when_modified:
    - '*.hcl'
    - '*.tf*'
    - ../../../../../modules/iam/group_policy/*.tf*
  dir: aws/env/dev/iam/groups/team-everyone
  workflow: terragrunt
- autoplan:
    enabled: true
    when_modified:
    - '*.hcl'
    - '*.tf*'
    - ../../../../../modules/iam/group_policy/*.tf*
  dir: aws/env/dev/iam/groups/team-xxx
  workflow: terragrunt
```
what i need is to add "values.yaml" to be in when_modified to be, like below
```
automerge: false
parallel_apply: true
parallel_plan: true
projects:
- autoplan:
    enabled: true
    when_modified:
    - '*.hcl'
    - '*.tf*'
    - 'values.yaml'
    - ../../../../../modules/iam/group_policy/*.tf*
  dir: aws/env/dev/iam/groups/team-everyone
  workflow: terragrunt
- autoplan:
    enabled: true
    when_modified:
    - '*.hcl'
    - '*.tf*'
    - 'values.yaml'
    - ../../../../../modules/iam/group_policy/*.tf*
  dir: aws/env/dev/iam/groups/team-xxx
  workflow: terragrunt
```
any way i can achieve this ?
