### ISSUE TITLE
unable to set proper root and project dir paths

### ISSUE THREAD

**Issue by ryanoolala** [transcend-io/terragrunt-atlantis-config#96]
My current terragrunt structure is as follows

```
├── account
│   ├── staging
│   │   ├── api-gateway
│   │   │    └── terragrunt.hcl
│   └── production
│   │   ├── api-gateway
│   │   │    └── terragrunt.hcl
└── modules
│   ├── api-gateway
│    │   └── main.tf
    
```

I would like to generate seperate `atlantis.yaml` as follows
atlantis.staging.yaml
```
- autoplan:
    enabled: false
    when_modified:
    - '*.hcl'
    - '*.tf*'
  dir: account/staging/api-gateway/
```

atlantis.production.yaml
```
- autoplan:
    enabled: false
    when_modified:
    - '*.hcl'
    - '*.tf*'
  dir: account/production/api-gateway/
```

In order to use different atlantis servers to reference to its respective atlantis.yaml based on environment. However when i try to make use of the `--root` parameter, it does not correctly reference the git root for the final dir, as if i were to set the following

`--root .` - I will get a merged atlantis.yaml with the correct dir reference
```
- autoplan:
    enabled: false
    when_modified:
    - '*.hcl'
    - '*.tf*'
  dir: account/staging/api-gateway/
- autoplan:
    enabled: false
    when_modified:
    - '*.hcl'
    - '*.tf*'
  dir: account/production/api-gateway/
`

`--root account` - I will get a merged atlantis.yaml with the *wrong* dir reference
```
- autoplan:
    enabled: false
    when_modified:
    - '*.hcl'
    - '*.tf*'
  dir: staging/api-gateway/
- autoplan:
    enabled: false
    when_modified:
    - '*.hcl'
    - '*.tf*'
  dir: production/api-gateway/
`

I will like to use `--root ./account/staging` to create my atlantis.staging.yaml and likewise for production, however this does not seem to be the use case for `--root`? Is there a method to achieve my desired yaml configuration? 

Thank you for looking at my issue.
